# File format: https://pre-commit.com/#plugins
# Supported hooks: https://pre-commit.com/hooks.html
# Running "make format" fixes most issues for you
repos:
  # python files
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-debugger==3.2.1
          - flake8-mypy==17.8.0
          - flake8-isort==4.0.0
          - flake8-blind-except==0.1.1
          - flake8-docstrings==1.5.0
          - mccabe==0.6.1
        language_version: python3.8
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.21'
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
