name: Run Tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        go-version: ["1.18"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go-version }}
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      run: go get ./...
    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.0.0
      with:
        version: "2022.1"
        install-go: false
        cache-key: ${{ matrix.go-version }}
    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... -v ./...
    - name: Upload to codecov
      uses: codecov/codecov-action@v1.0.6
